MaryTTS/Dockerfile, MaryTTS/build.json, picoTTS/Dockerfile, picoTTS/build.json
Update the Dockerfile and build.json for issue #8 and #9. 
Please check detail build result: [Travis CI build result](https://travis-ci.org/ClarkChiu/Hassio-Addons/builds/593447038).
=> Update the Dockerfile and build.json for issue #8 and #9.

mopidy/CHANGELOG.md, mopidy/Dockerfile, mopidy/build.json, mopidy/config.json
=> updated mopidy versions

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/Dockerfile, ICantBelieveItsNotValetudo/config.json
=> pulling the version requested in the issue

mopidy/CHANGELOG.md, mopidy/Dockerfile, mopidy/config.json, mopidy/mopidy.conf, mopidy/run.sh
* Adds Youtube extension, closes #22 
* Update mopidy
=> Mopidy update

.scripts/build.sh
Build no plugins which weren't changed
=> Compare with master on push

git-exporter/CHANGELOG.md, git-exporter/Dockerfile, git-exporter/README.md, git-exporter/config.json, git-exporter/run.sh
Update to latest homeassistant lovelace configs for exporter
=> Exporter update

picoTTS/README.md
Corrected URL used for testing.
=> Update README.md with correct syntax for URL

git-exporter/CHANGELOG.md, git-exporter/DOCS.md, git-exporter/README.md, git-exporter/config.json, git-exporter/run.sh
=> Exporter improvements

mpd/CHANGELOG.md, mpd/DOCS.md, mpd/README.md, mpd/config.json, mpd/run.sh
=> Added option to use own mpd configuration.

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/Dockerfile, ICantBelieveItsNotValetudo/config.json
Fixes also bugs with valetudo 0.5.2
=> Update to latest ICantBelieveItsNotValetudo

syncthing/CHANGELOG.md, syncthing/Dockerfile, syncthing/README.md, syncthing/config.json
=> Add Syncthing ssl mapping and update to latest

MaryTTS/CHANGELOG.md, MaryTTS/Dockerfile, MaryTTS/build.json, MaryTTS/config.json, MaryTTS/root/etc/cont-init.d/01-install-voice-pack, MaryTTS/root/etc/services.d/marytts/run, picoTTS/CHANGELOG.md, picoTTS/Dockerfile, picoTTS/build.json, picoTTS/config.json, picoTTS/root/etc/services.d/picotts/run
=> Update system around MaryTTS and picoTTS

mpd/CHANGELOG.md, mpd/DOCS.md, mpd/config.json, mpd/root/etc/cont-init.d/setup-settings
=> [MPD] Config fix and HTTPd output

valetudo-mapper/CHANGELOG.md, valetudo-mapper/Dockerfile, valetudo-mapper/build.json, valetudo-mapper/config.json
Update valetudo-mapper to include the changes from #134.
closes #134
=> Update valetudo-mapper to latest commit and alpine

.github/workflows/check-pr.yml, valetudo-mapper/CHANGELOG.md, valetudo-mapper/README.md, valetudo-mapper/config.json
=> Fix valetudo-mapper config

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/Dockerfile, ICantBelieveItsNotValetudo/config.json, ICantBelieveItsNotValetudo/root/etc/services.d/Server/run, ICantBelieveItsNotValetudo/root/server/main.js, ICantBelieveItsNotValetudo/root/server/package.json
* Add small webserver to apply style to the map on the sidebar.
* Update ICantBelieveItsNotValetudo to latest version
see also #142
=> [ICantBelieveItsNotValetudo] Style and Update

git-exporter/root/run.sh
It should fix #135, but it looks weird
=> [git-exporter] temporary fix #135

.github/workflows/check-pr.yaml, .github/workflows/lint-checks.yaml
Separate lint checks and added version check
closes #154
=> CI improvements

pigpio/CHANGELOG.md, pigpio/Dockerfile, pigpio/config.json
=> Update to pigpio to v78

ICantBelieveItsNotValetudo/README.md
Updated ICantBelieveItsNotValetudo README.md to better document the `core_mosquitto` address usage - related: #158
=> Better document usage of the `core_mosquitto` address in ICantBelieveItsNotValetudo

mpd/CHANGELOG.md, mpd/Dockerfile, mpd/config.json, mpd/root/etc/cont-init.d/setup-folders, mpd/root/etc/fix-attrs.d/mpd, mpd/root/etc/fix-attrs.d/mpd-permissions, mpd/root/etc/fix-attrs.d/ympd
=> Fixed missing permissions for MPD

pigpio/CHANGELOG.md, pigpio/Dockerfile, pigpio/config.json, pigpio/root/etc/services.d/pigpio/run
=> [pigpio] Reroute pipe files to work in addon environment

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/Dockerfile, ICantBelieveItsNotValetudo/config.json, valetudo-mapper/CHANGELOG.md, valetudo-mapper/config.json
=> Allow Valetudo's mqtt anonymous access

.github/workflows/check-pr.yaml, .github/workflows/master-push.yaml, container-stats/CHANGELOG.md, container-stats/Dockerfile, container-stats/build.json, container-stats/config.json
And testing of using buildx for docker image assembly
=> Build image update

.github/paths-filter.yml, .github/workflows/check-pr.yaml, .github/workflows/master-push.yaml, rsync-local/CHANGELOG.md, rsync-local/Dockerfile, rsync-local/build.json, rsync-local/config.json, rsync/CHANGELOG.md, rsync/Dockerfile, rsync/build.json, rsync/config.json
Only create tasks for addons which needs a build.
=> Better check for changed files in addons

MaryTTS/CHANGELOG.md, MaryTTS/Dockerfile, MaryTTS/config.json
=> Recover MaryTTS environment

mpd/CHANGELOG.md, mpd/config.json, mpd/root/etc/cont-init.d/setup-folders, mpd/root/etc/cont-init.d/setup-settings
Add setting for the music and playlists, as proposed here #152?
=> [mpd] Add option for custom folders

.github/workflows/check-pr.yaml, .github/workflows/master-push.yaml, mpd/CHANGELOG.md
=> Fix builder error

mpd/CHANGELOG.md, mpd/DOCS.md, mpd/config.json, mpd/root/etc/cont-init.d/setup-settings
=> [mpd] Fix option overwriting custom config

git-exporter/CHANGELOG.md, git-exporter/Dockerfile, git-exporter/config.json, git-exporter/root/run.sh
=> Url encode git password.

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/Dockerfile, ICantBelieveItsNotValetudo/README.md, ICantBelieveItsNotValetudo/config.json, ICantBelieveItsNotValetudo/root/app/config-template.jq, ICantBelieveItsNotValetudo/root/etc/services.d/Server/run, ICantBelieveItsNotValetudo/root/server/main.js, ICantBelieveItsNotValetudo/root/server/package.json
=> Update ICBINV to 2021.3.1

git-exporter/CHANGELOG.md, git-exporter/DOCS.md, git-exporter/Dockerfile, git-exporter/config.json, git-exporter/root/run.sh
=> [git-exporter] Dont encode password if its a token

git-exporter/CHANGELOG.md, git-exporter/DOCS.md, git-exporter/config.json
Taking the changes from @fliphess and added the necessary Changelog changes.
Sry for not responding to your stale MR 😥
Part of #243
=> Add docs about special regex chars on git-exporter.

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/Dockerfile, ICantBelieveItsNotValetudo/config.json
Content of #250 with additions to fix the dependencies and lint issues
=> Update ICBINV to 2021.6.0

pigpio/CHANGELOG.md, pigpio/Dockerfile, pigpio/README.md, pigpio/build.json, pigpio/config.json
=> Add aarch64 variant for pigpio

syncthing/CHANGELOG.md, syncthing/Dockerfile, syncthing/README.md, syncthing/config.json
=> Add storage consumption notice to syncthing readme

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/Dockerfile, ICantBelieveItsNotValetudo/build.json, ICantBelieveItsNotValetudo/config.json, valetudo-mapper/CHANGELOG.md, valetudo-mapper/Dockerfile, valetudo-mapper/build.json, valetudo-mapper/config.json
* Adjusts schema validation (closes #264)
* Update valetudo-mapper and dependencies
=> Update schema validation on Valetudo addons to include the port

git-exporter/CHANGELOG.md, git-exporter/DOCS.md, git-exporter/Dockerfile, git-exporter/build.json, git-exporter/config.json, git-exporter/root/run.sh
* Version updates
* Configurable branch name
=> Git exporter updates

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/Dockerfile, ICantBelieveItsNotValetudo/config.json
=> [ICBINV] Update ICBINV to 2021.12.0

ICantBelieveItsNotValetudo/CHANGELOG.md, ICantBelieveItsNotValetudo/config.json
=> [ICBINV] Add missing crop and padding settings

git-exporter/CHANGELOG.md, git-exporter/Dockerfile, git-exporter/config.json, git-exporter/root/run.sh
=> [git-exporter] Exclude log files from export

git-exporter/CHANGELOG.md, git-exporter/config.json, git-exporter/root/run.sh
=> [git-exporter] Ignore logs over config

vnc-viewer/CHANGELOG.md, vnc-viewer/Dockerfile, vnc-viewer/build.json, vnc-viewer/config.json, vnc-viewer/root/etc/cont-init.d/setup-novnc-ingress, vnc-viewer/root/etc/services.d/noVNC/run
Update noVNC version and fix connections from https instances.
=> [vnc-viewer] update-versions

mopidy/CHANGELOG.md, mopidy/Dockerfile, mopidy/config.json
=> :bug: [mopidy] Fix not starting mopiy

syncthing/README.md
I tried to keep it short and refer to other doc/manuals while still mentioning the relevant technical info.
=> [syncthing] Add note and howto on ext storage to README

syncthing/CHANGELOG.md, syncthing/Dockerfile, syncthing/config.yaml
Update syncthing to [v1.21](https://github.com/syncthing/syncthing/releases/tag/v1.21.0)
=> [syncthing] Update syncthing

git-exporter/config.yaml, git-exporter/root/run.sh
Addresses #314
I haven't been able to test this on my existing install because I am not sure if it's possible to add an add-on repository from non-default branch and changing repo metadata would pollute this PR.
=> [git-exporter] Allow customising secret patterns

syncthing/CHANGELOG.md, syncthing/Dockerfile, syncthing/config.yaml
=> Merge into Main

rsync/CHANGELOG.md, rsync/DOCS.md, rsync/Dockerfile, rsync/build.yaml, rsync/config.yaml, rsync/root/run.sh
=> Rsync updates

syncthing/README.md
=> Update Migration Link in README.md
